"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowRight, Check, ChevronDown, Menu, Phone, Play, Sparkles, X } from "lucide-react";

const navigation = [["What we make", "#services"], ["Industries", "#industries"], ["Why now", "#why-now"], ["Pricing", "#packages"], ["Process", "#process"]];
const comparison = [["Chase a crew, drone operator, editor, and designer", "Send approved photos or footage"], ["Manage scheduling, handoffs, and the wait for the next edit", "Approve the direction before paid generation"], ["Treat each listing like a one-off production project", "Turn one approved image set into a focused campaign"], ["Post a photo gallery and hope it gets attention", "Create platform-ready films, stories, and social reels"], ["Start from zero when inventory changes", "Use a repeatable content system"]];
const industries = [["Real estate and Airbnb", "Walkthroughs, room reveals, amenities, open houses, and booking-focused previews."], ["RVs and motor coaches", "Floor plans, storage, interiors, road-use stories, and changing dealer inventory."], ["Exotic and luxury auto", "Launch films, collector stories, craftsmanship, configuration, and inventory spotlights."], ["Yachts and boats", "Exterior lines, decks, interiors, charter experiences, refits, and broker inventory."], ["Private aviation", "Cabin experience, aircraft details, charter stories, routes, and service distinctions."], ["Private events and venues", "Guest flow, ceremony setups, hospitality, celebration, and the atmosphere of the space."]];
const steps = [["01", "Share your assets.", "Send a website, listing link, image folder, brand references, product details, and the offer you want to promote."], ["02", "Approve the direction.", "We shape the information into a creative concept, visual mood, sequence, and message before producing the final content."], ["03", "We create the videos.", "Your approved assets become cinematic short-form videos designed for the formats you select."], ["04", "Receive the content kit.", "Get finished videos, captions, hashtag suggestions, calls to action, and any agreed alternate formats."], ["05", "Publish and learn.", "Use the content on social channels, paid campaigns, listings, and sales follow-up."]];
const packages = [["Signature", "$1,500", "8 short-form films", "15 to 30 seconds each", "2 consolidated revision rounds", "Choose Signature"], ["Authority", "$2,750", "16 short-form films", "15 to 30 seconds each", "Revision scope confirmed before quoting", "Choose Authority"], ["Portfolio", "$4,500", "24 short-form and 2 long-form films", "Long-form films up to 5 minutes", "Revision scope confirmed before quoting", "Ask About Portfolio"]];
const faqs = [["Do you need to visit our location?", "Not always. We can begin with approved photography, video, listing links, product information, and brand references. On-site production can still be recommended where physical capture is essential."], ["Can we choose vertical or landscape video?", "Yes. Packages can include 9:16 vertical, 16:9 landscape, or an agreed mix of both."], ["How long are the videos?", "Standard short-form videos are approximately 15 to 30 seconds. The Portfolio package can include two long-form videos of up to 5 minutes, subject to scope and available assets."], ["Can you write the caption too?", "Yes. Captions, hashtag suggestions, and calls to action are included in the monthly packages."], ["Can you put me inside the video?", "A digital host or likeness integration can be added when the client provides explicit approval and the required reference material."], ["Will the videos be accurate?", "We use a human review and approval process. The client is responsible for confirming factual details, specifications, pricing, availability, compliance language, and rights to supplied assets before publishing."], ["Can you post the content for us?", "Yes. Monthly scheduling and publishing is an optional $750/month service, subject to access and permissions."], ["Do you guarantee more sales?", "No. The service is designed to improve the quality, consistency, and volume of marketing content. Results depend on the offer, audience, distribution, sales process, inventory, timing, and many other factors."]];

function Button({ children, href = "#contact" }: { children: React.ReactNode; href?: string }) {
  return <a className="button" href={href}>{children}<ArrowRight size={16} /></a>;
}

export default function Page() {
  const [open, setOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const listener = () => setScrolled(window.scrollY > 24);
    window.addEventListener("scroll", listener);
    return () => window.removeEventListener("scroll", listener);
  }, []);

  return (
    <main>
      <header className={scrolled ? "header header-solid" : "header"}>
        <a href="#top" className="brand">EMPOSSIBLE<span>.</span></a>
        <nav className="desktop-nav">{navigation.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav>
        <div className="header-actions"><a href="#contact" className="header-cta">Request a content audit</a><button className="menu-button" aria-label="Open menu" onClick={() => setOpen(true)}><Menu /></button></div>
      </header>
      {open && <div className="mobile-menu"><button onClick={() => setOpen(false)} aria-label="Close menu"><X /></button>{navigation.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}<Button>Request a content audit</Button></div>}

      <section className="hero" id="top"><div className="hero-grid" /><div className="hero-orb" /><div className="hero-arc" /><div className="wrap hero-content centered"><p className="eyebrow"><Sparkles size={13} /> CINEMATIC CONTENT FROM ASSETS YOU ALREADY OWN</p><h1>Make the experience <em>possible to feel.</em></h1><p className="hero-copy">EMPOSSIBLE turns approved photography and footage into cinematic films, social reels, listing stories, and campaign-ready content for premium inventory and spaces.</p><div className="button-row"><Button>Request a content audit</Button></div></div><p className="hero-index">SCROLL TO ENTER <ArrowDownRight size={16} /></p></section>

      <section className="section" id="services"><div className="wrap centered-section"><div className="image-stage"><div className="placeholder-label">SOURCE-LED PRODUCTION</div><div className="image-window"><span>ONE REAL ASSET. A CLEAR CINEMATIC DIRECTION.</span><div className="window-gradient" /></div></div><div className="copy-column"><p className="eyebrow">THE OPPORTUNITY</p><h2>You already have the raw material. We give it movement, sequence, and a point of view.</h2><p>One approved image set can become a focused campaign instead of a gallery that disappears after launch.</p><p>Every film starts with source review, factual checks, a clear direction, and an approval gate.</p></div></div></section>

      <section className="section comparison" id="why-now"><div className="wrap centered-section"><p className="eyebrow">THE OLD WAY</p><h2>A standout listing film used to mean chasing a crew, a drone operator, an editor, and a designer.</h2><p className="section-intro">Then came the scheduling, the handoffs, and the wait for the next edit.</p><div className="comparison-list big-comparison">{comparison.map(([oldWay, newWay]) => <div className="comparison-row" key={oldWay}><div><span className="compare-label">THE OLD WAY</span><p>{oldWay}</p></div><div><span className="compare-label cinematic-label">THE EMPOSSIBLE WAY</span><p className="new-way">{newWay}</p></div></div>)}</div></div></section>

      <section className="section benefits"><div className="wrap centered-section"><p className="eyebrow">THE EMPOSSIBLE WAY</p><h2>Send the approved photos or footage. We turn them into cinematic, platform-ready listing content.</h2><div className="benefit-copy"><p>Do not manage a production crew for every property, vehicle, yacht, aircraft, or stay. Start with the assets you already have, then approve the direction before paid generation.</p><p>The goal is to give buyers, guests, and customers a stronger first impression before they buy, book, or visit.</p></div></div></section>

      <section className="section industries" id="industries"><div className="wrap centered-section"><p className="eyebrow">BUILT FOR</p><h2>High-value things people need to imagine before they buy, book, or visit.</h2><div className="industry-grid">{industries.map(([title, text]) => <article className="industry-card" key={title}><div className="card-visual" /><h3>{title}</h3><p>{text}</p><a href="#contact">Show us what you are selling <ArrowRight size={15} /></a></article>)}</div></div></section>

      <section className="section process" id="process"><div className="wrap centered-section"><p className="eyebrow">THE PROCESS</p><h2>Clear decisions before paid generation.</h2><div className="process-line" /><div className="steps">{steps.slice(0, 4).map(([number, title, text]) => <article className="step" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="section packages" id="packages"><div className="wrap centered-section"><p className="eyebrow">PRICING FOUNDATION</p><div className="starter"><div><span className="starter-tag">START WITH ONE</span><h2>See what one listing can become before you commit.</h2></div><div><p className="starter-price">$300 <small>one time</small></p><p>One 15 to 30 second cinematic video for a property, Airbnb listing, vehicle, jet, yacht, RV, mansion, or venue. A clear first experience before choosing a recurring content plan.</p><Button>Try one video</Button></div></div><div className="package-grid">{packages.map(([name, price, output, detail, revisions, cta], index) => <article className={index === 1 ? "package featured" : "package"} key={name}>{index === 1 && <span className="recommended">HIGH-VOLUME RHYTHM</span>}<p className="package-name">{name}</p><p className="package-price">{price}<small>/month</small></p><div className="package-rule" /><h3>{output}</h3><p>{detail}</p><p>{revisions}</p><ul><li><Check size={16} /> Brand and source intake</li><li><Check size={16} /> Content and listing map</li><li><Check size={16} /> Brand title system</li><li><Check size={16} /> Caption and CTA suggestions</li><li><Check size={16} /> Human review gates</li></ul><Button>{cta}</Button><p className="package-note">Asset limits, turnaround, generation budget, music rights, derivatives, publishing, and revisions are confirmed in the written quote.</p></article>)}</div></div></section>

      <section className="section portfolio" id="portfolio"><div className="wrap centered-section"><p className="eyebrow">THE FIRST IMPRESSION</p><h2>Let the Work Create the <em>First Impression.</em></h2><div className="featured-reel"><div className="reel-overlay"><span>FEATURED WORK / COMING SOON</span><button aria-label="Play featured portfolio video"><Play fill="currentColor" size={22} /></button><strong>Before: approved listing and inventory images.<br />After: cinematic social-ready video.</strong></div></div><div className="reel-grid">{["Concept Work", "Sample Transformation", "Portfolio Video Coming Soon"].map((label, index) => <div className="reel" key={label}><span>0{index + 1}</span><p>{label}</p><Play size={16} /></div>)}</div></div></section>

      <section className="section partnership" id="partnership"><div className="wrap centered-section"><p className="eyebrow">CUSTOM ENGAGEMENT</p><h2>Need More Than a Monthly <em>Video Package?</em></h2><p className="section-intro">If your team has a large inventory, multiple locations, frequent launches, or an active sales pipeline, we can explore a custom content partnership. We can plan your creative calendar, prioritize the inventory that needs attention, create campaign variations, and coordinate content around your sales goals.</p><p className="section-intro">This is not a standard package. Partnerships are structured around inventory volume, campaign goals, attribution, and commercial terms.</p><Button>Ask About a Custom Partnership</Button></div></section>

      <section className="section faq" id="faq"><div className="wrap centered-section"><p className="eyebrow">CLARITY</p><h2>Questions Before We Start?</h2><p className="section-intro">Every project begins with approved assets, clear direction, and a review process designed to keep the work aligned with your brand.</p><div className="accordion">{faqs.map(([question, answer], index) => <div className="faq-item" key={question}><button aria-expanded={activeFaq === index} onClick={() => setActiveFaq(activeFaq === index ? null : index)}>{question}<ChevronDown className={activeFaq === index ? "chevron rotate" : "chevron"} /></button>{activeFaq === index && <p>{answer}</p>}</div>)}</div></div></section>

      <section className="section contact" id="contact"><div className="wrap centered-section"><p className="eyebrow">START THE CONVERSATION</p><h2>Show us the listing, inventory, or space that deserves a stronger first impression.</h2><p className="section-intro">Call or text 216-633-2029. A new EMPOSSIBLE social handle and booking destination will replace the existing account links before launch.</p><div className="contact-actions"><a className="contact-card" href="tel:+12166332029"><Phone size={22} /><span>Call EMPOSSIBLE</span><strong>216-633-2029</strong></a><a className="contact-card" href="sms:+12166332029"><Phone size={22} /><span>Text EMPOSSIBLE</span><strong>216-633-2029</strong></a></div><Button href="tel:+12166332029">Call EMPOSSIBLE</Button></div></section>

      <footer><div className="wrap footer-inner centered-section"><a href="#top" className="brand">EMPOSSIBLE<span>.</span></a><div className="footer-links">{navigation.map(([label, href]) => <a href={href} key={label}>{label}</a>)}<a href="#contact">Contact</a></div><small>All claims, availability, likenesses, and conceptual visuals require review and approval before publication.</small></div></footer>
    </main>
  );
}
